import React from 'react';
import { useFootprintStore } from '../stores/useFootprintStore';
import { useFootprintWebSocket } from '../hooks/useFootprintWebSocket';
import { FootprintChart } from '../components/footprint/FootprintChart';
import { FootprintControlPanel } from '../components/footprint/FootprintControlPanel';
import { DeltaProfile } from '../components/footprint/DeltaProfile';

const baseUrl = () => import.meta.env.VITE_API_URL || 'http://localhost:8000';

export const OrderFlowFootprintView: React.FC = () => {
  useFootprintWebSocket();
  const {
    instrument, timeframe, imbalanceRatioPct, currentCandle, history, connectionStatus,
    setInstrument, setTimeframe, setImbalanceRatioPct,
  } = useFootprintStore();

  const handleRatioChange = (ratio: number) => {
    setImbalanceRatioPct(ratio);
    fetch(`${baseUrl()}/api/v1/footprint/imbalance-ratio`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ ratio_pct: ratio }),
    }).catch(() => {
      // Non-fatal — rendering uses the local ratio regardless; this call
      // only keeps the backend's shared/global default in sync.
    });
  };

  const visibleCandles = currentCandle ? [...history, currentCandle] : history;

  return (
    <div className="space-y-6 select-none">
      <div>
        <h2 className="text-zinc-100 font-sans font-bold text-lg uppercase tracking-wider">Order Flow Footprint Chart</h2>
        <p className="text-xs text-zinc-400 font-sans mt-0.5 font-medium">
          Bid/ask footprint, diagonal &amp; stacked imbalance detection for NIFTY / BANKNIFTY / SENSEX Futures.
        </p>
      </div>

      <div className="bg-amber-950/30 border border-amber-900/50 rounded-lg px-4 py-2.5 text-xs text-amber-300 font-mono">
        SIMULATED DATA — no real Level 2 futures depth is wired into this app yet (the live Upstox stream
        runs in LTP-only mode against index spot instruments, not full-depth futures). Ticks here are
        generated by a local random-walk simulator for demonstrating the footprint/imbalance visualization.
      </div>

      <FootprintControlPanel
        instrument={instrument}
        timeframe={timeframe}
        imbalanceRatioPct={imbalanceRatioPct}
        connectionStatus={connectionStatus}
        onInstrumentChange={setInstrument}
        onTimeframeChange={setTimeframe}
        onImbalanceRatioChange={handleRatioChange}
      />

      <div className="h-[600px] w-full bg-zinc-900 border border-zinc-800 rounded-lg p-2">
        <FootprintChart candles={visibleCandles} imbalanceRatioPct={imbalanceRatioPct} />
      </div>

      <DeltaProfile candles={visibleCandles} />
    </div>
  );
};

export default OrderFlowFootprintView;
